/*
 * generated by Xtext
 */
package org.ustok.checklist.cfg.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ustok.checklist.cfg.ui.internal.ChecklistActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChecklistExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ChecklistActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ChecklistActivator.getInstance().getInjector(ChecklistActivator.ORG_USTOK_CHECKLIST_CFG_CHECKLIST);
	}
	
}
