/*
 * generated by Xtext
 */
package org.ustok.checklist.cfg.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractChecklistValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.ustok.checklist.cfg.checklist.ChecklistPackage.eINSTANCE);
		return result;
	}
}
