/*
 * generated by Xtext
 */
package org.ustok.checklist.cfg;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ChecklistRuntimeModule extends org.ustok.checklist.cfg.AbstractChecklistRuntimeModule {

}
