/*
 * generated by Xtext
 */
package org.ustok.checklist.cfg.ui.contentassist

import org.ustok.checklist.cfg.ui.contentassist.AbstractChecklistProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ChecklistProposalProvider extends AbstractChecklistProposalProvider {
}
