/*
 * generated by Xtext
 */
package org.ustok.checklist.cfg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ChecklistUiModule extends org.ustok.checklist.cfg.ui.AbstractChecklistUiModule {
	public ChecklistUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
