/**
 * generated by Xtext
 */
package org.ustok.checklist.cfg.validation;

import org.ustok.checklist.cfg.validation.AbstractChecklistValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ChecklistValidator extends AbstractChecklistValidator {
}
