/*
* generated by Xtext
*/
package org.ustok.checklist.cfg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ChecklistAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/ustok/checklist/cfg/parser/antlr/internal/InternalChecklist.tokens");
	}
}
